### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by viperownageGITHUB** [GZer/MyKolbot#2]
Could u give a short explanation on how to use it? I saw u wrote u try to keep it a "plug and play" .. I am already using the Kolbot, but never with autoequip. I've tried it and it never works.
Just a short step by step explanation from downloading to starting it? 
And is it right, that u need a rusher for the char? or is it  questin and lvling all alone?

**Comment by GZer** [comment]
Hi no you do not need a rusher the bots should run from lvl 1-90 by themselves.
You need to help them change acts and hire mercs because I couldn't be bothered figuring that out.

Download the zip and follow the ReadMe instructions, there is a getting started section that should help you but essentially you need to name characters the same as the script .js files and customise your own pickit filters.
